version: 0.0
os: linux
files:
  - source: NetCoreWorker/bin/release/netcoreapp3.0/
    destination: /opt/netcoreworker
  - source: scripts/workerservice.service
    destination: /etc/systemd/system
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root

    - location: scripts/install_dotnetcore
      timeout: 500
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
