#!/bin/bash
cd /home/ubuntu/

# use systemd to start and monitor dotnet application
systemctl enable workerservice.service
systemctl start workerservice.service

# start apache
# systemctl restart apache2.service